<Workspace Version="0.7.6.3422" X="17350.6637255903" Y="14519.5579352644" zoom="0.713113851324522" Description="" Category="" Name="Home">
  <Elements>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="918f7dc4-e6d0-4d6b-9b51-c329d02db2b2" nickname="Point.ByCoordinates" x="-24471.4286892823" y="-20038.7078255326" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="fb265a32-22b0-4d2a-b4f7-26b28bc90c10" nickname="Point.ByCoordinates" x="-24471.4286892823" y="-19740.8597671717" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="e594468a-4123-44b4-8708-84b31915b703" nickname="Point.ByCoordinates" x="-24470.1390765397" y="-19888.415696243" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="64155f51-0808-47f8-be8d-0fb57485b1e3" nickname="Point.ByCoordinates" x="-24469.5492826162" y="-19598.9498803032" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.DoubleInput type="Dynamo.Nodes.DoubleInput" guid="4f378cbb-3c5d-4496-b11b-e74d16300d48" nickname="Number" x="-24609.192097963" y="-19704.0311350431" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Double value="10" />
    </Dynamo.Nodes.DoubleInput>
    <Dynamo.Nodes.DoubleInput type="Dynamo.Nodes.DoubleInput" guid="e8e066b3-31a0-48ad-bf0f-d5e0e27a1c20" nickname="Number" x="-24609.192097963" y="-19586.6763754658" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Double value="15" />
    </Dynamo.Nodes.DoubleInput>
    <Dynamo.Nodes.DoubleInput type="Dynamo.Nodes.DoubleInput" guid="bc1ea099-1645-4e28-b574-19385b4d812b" nickname="Number" x="-24609.192097963" y="-19857.4950514135" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Double value="5" />
    </Dynamo.Nodes.DoubleInput>
    <DSCoreNodesUI.CreateList type="DSCoreNodesUI.CreateList" guid="fc159a46-e230-462d-91e7-ac387a527d64" nickname="List.Create" x="-24180.0283403342" y="-19861.4432371731" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="4" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="7979f6ce-63b6-4cfb-9872-9d05812a111c" nickname="Line.ByStartPointEndPoint" x="-23755.1545802998" y="-20044.7180525039" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="d200379e-5c8c-4f8b-968d-2f0887223d68" nickname="NurbsCurve.ByPoints" x="-23753.2993692271" y="-19749.5634852303" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.NurbsCurve.ByPoints@Autodesk.DesignScript.Geometry.Point[]" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="835b1ec2-52ca-4b63-9a1f-2a0dde80b497" nickname="PolyCurve.ByPoints" x="-23758.4578201975" y="-19648.9736913069" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.PolyCurve.ByPoints@Autodesk.DesignScript.Geometry.Point[],bool">
      <PortInfo index="1" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="eaae1aa1-4188-4897-8ae4-a743ac654a51" nickname="Curve.Length" x="-23167.7427863276" y="-19987.0611419685" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.Length" />
    <DSCoreNodesUI.BoolSelector type="DSCoreNodesUI.BoolSelector" guid="6e4f5b2b-2389-451b-9545-9dea13431b8b" nickname="Boolean" x="-23930.9783744459" y="-19851.6236889259" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Boolean>True</System.Boolean>
    </DSCoreNodesUI.BoolSelector>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="8ba3309a-6ded-4059-a074-fa0c2b291919" nickname="NurbsCurve.ByControlPoints" x="-23754.5915986248" y="-19921.0404200555" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.NurbsCurve.ByControlPoints@Autodesk.DesignScript.Geometry.Point[],int,bool">
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="2c8d0d14-0440-438c-b81c-dcdeefc1b77e" nickname="Curve.PointAtParameter" x="-23180.3194152019" y="-19793.7458270855" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double">
      <PortInfo index="1" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.CodeBlockNodeModel type="Dynamo.Nodes.CodeBlockNodeModel" guid="7820af5f-481d-4af7-9b35-9e608a64b96d" nickname="Code Block" x="-23314.8521241916" y="-19684.9903711898" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="0..1..#20;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="f4ef10a1-1aed-49d5-8474-39cdbdf5fea6" nickname="ModelCurve.ByCurve" x="-23179.0287976515" y="-19544.3817204082" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="RevitNodes.dll" function="Revit.Elements.ModelCurve.ByCurve@Autodesk.DesignScript.Geometry.Curve" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="918f7dc4-e6d0-4d6b-9b51-c329d02db2b2" start_index="0" end="fc159a46-e230-462d-91e7-ac387a527d64" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="918f7dc4-e6d0-4d6b-9b51-c329d02db2b2" start_index="0" end="7979f6ce-63b6-4cfb-9872-9d05812a111c" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="fb265a32-22b0-4d2a-b4f7-26b28bc90c10" start_index="0" end="fc159a46-e230-462d-91e7-ac387a527d64" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="e594468a-4123-44b4-8708-84b31915b703" start_index="0" end="fc159a46-e230-462d-91e7-ac387a527d64" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="e594468a-4123-44b4-8708-84b31915b703" start_index="0" end="7979f6ce-63b6-4cfb-9872-9d05812a111c" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="64155f51-0808-47f8-be8d-0fb57485b1e3" start_index="0" end="fc159a46-e230-462d-91e7-ac387a527d64" end_index="3" portType="0" />
    <Dynamo.Models.ConnectorModel start="4f378cbb-3c5d-4496-b11b-e74d16300d48" start_index="0" end="fb265a32-22b0-4d2a-b4f7-26b28bc90c10" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="4f378cbb-3c5d-4496-b11b-e74d16300d48" start_index="0" end="fb265a32-22b0-4d2a-b4f7-26b28bc90c10" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="e8e066b3-31a0-48ad-bf0f-d5e0e27a1c20" start_index="0" end="64155f51-0808-47f8-be8d-0fb57485b1e3" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="bc1ea099-1645-4e28-b574-19385b4d812b" start_index="0" end="e594468a-4123-44b4-8708-84b31915b703" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="fc159a46-e230-462d-91e7-ac387a527d64" start_index="0" end="d200379e-5c8c-4f8b-968d-2f0887223d68" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="fc159a46-e230-462d-91e7-ac387a527d64" start_index="0" end="835b1ec2-52ca-4b63-9a1f-2a0dde80b497" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="fc159a46-e230-462d-91e7-ac387a527d64" start_index="0" end="8ba3309a-6ded-4059-a074-fa0c2b291919" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="7979f6ce-63b6-4cfb-9872-9d05812a111c" start_index="0" end="eaae1aa1-4188-4897-8ae4-a743ac654a51" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="835b1ec2-52ca-4b63-9a1f-2a0dde80b497" start_index="0" end="2c8d0d14-0440-438c-b81c-dcdeefc1b77e" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="835b1ec2-52ca-4b63-9a1f-2a0dde80b497" start_index="0" end="f4ef10a1-1aed-49d5-8474-39cdbdf5fea6" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="6e4f5b2b-2389-451b-9545-9dea13431b8b" start_index="0" end="8ba3309a-6ded-4059-a074-fa0c2b291919" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="7820af5f-481d-4af7-9b35-9e608a64b96d" start_index="0" end="2c8d0d14-0440-438c-b81c-dcdeefc1b77e" end_index="1" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Models.NoteModel text="Curves, Polycurves (collections of Curves), Nurbs, and Lines all derive from &quot;Curves&quot;, and so all Curve &quot;Actions&quot; and &quot;Queries&quot; can be done to all of them" x="-23240.3161700635" y="-19873.7297569865" />
    <Dynamo.Models.NoteModel text="Multiple creation methods exist for most curves.  " x="-23755.3612463271" y="-20085.2107041965" />
    <Dynamo.Models.NoteModel text="Pass any curve element to Revit Elements that are driven by Lines or other Curves to create them" x="-23230.477265241" y="-19597.6691441897" />
  </Notes>
</Workspace>