<Workspace Version="1.0.1.1821" X="130.097546502025" Y="351.643411740913" zoom="0.906217674817656" Name="Home" Description="" RunType="Manual" RunPeriod="100" HasRunWithoutCrash="False">
  <NamespaceResolutionMap>
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="16aa9869-04a9-4577-889c-e8b99114eaa5" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="169" y="4.21833333333331" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Autodesk.Point.ByCoordinates(0..end, 0,0);" ShouldFocus="false" />
    <CoreNodeModels.Input.DoubleInput guid="8d9300ea-8f8a-4c2c-b010-a26e3f00ff6d" type="CoreNodeModels.Input.DoubleInput" nickname="Number" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Double value="5" />
    </CoreNodeModels.Input.DoubleInput>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9af28bf1-e5ea-419a-95c8-d4932f503377" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ReferencePoint.ByPoint" x="687" y="0" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.ReferencePoint.ByPoint@Autodesk.DesignScript.Geometry.Point" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="16aa9869-04a9-4577-889c-e8b99114eaa5" start_index="0" end="9af28bf1-e5ea-419a-95c8-d4932f503377" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8d9300ea-8f8a-4c2c-b010-a26e3f00ff6d" start_index="0" end="16aa9869-04a9-4577-889c-e8b99114eaa5" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>